### ISSUE TITLE
TtcnComplete

### ISSUE THREAD

**Issue by HuiMi24** [karolwiniarski/language-ttcn-3#1]
Great, you converted Sublime TTCN highlight to Atom. if you have further plan to migrate TtcnComplete to Atom. Please let me know. 
Thank you.

**Comment by karolwiniarski** [comment]
Hi!
I’m not sure. Highlighting is sufficient for me at the moment. Maybe I will implement snippets and completions. Unfortunately I have very limited time for additional projects and I think that this one might not gain popularity, so probably I will not migrate whole package.
